driving_mis/driving_mis/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', views.home_redirect, name='home'),
    path('login/', views.login_page, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('admin/', include("userAdmin.urls")),
    path('staffs/', include('userStaff.urls')),
]

driving_mis/userAdmin/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'userAdmin'

urlpatterns = [
    
    path('dashboard/', views.dashboard_page, name='dashboard'),
    path('students/', views.students_page, name='students'),
    path('payments/', views.payments_page, name='payments'),
    path('staffs/', views.staffs_page, name='staffs'),

    path('students/add/', views.student_add, name='addStudent'),
    path('students/update/<slug:slug>/', views.student_update, name='updateStudent'),
    path('students/delete/<slug:slug>/', views.student_delete, name='deleteStudent'),

    path('payments/add/', views.payment_add, name='addPayment'),
    path('payments/update/<int:id>/', views.payment_update, name='updatePayment'),
    path('payments/delete/<int:id>/', views.payment_delete, name='deletePayment'),

    path('staffs/add/', views.staff_add, name='addStaff'),
    path('staffs/update/<int:staff_id>/', views.staff_update, name='updateStaff'),
    path('staffs/delete/<int:staff_id>/', views.staff_delete, name='deleteStaff'),
]

driving_mis/userAdmin/models.py
from django.db import models
from django.utils.text import slugify
import uuid

class Student(models.Model):
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=15)
    address = models.TextField()
    course = models.CharField(
        max_length=1,
        choices=[
            ('A', 'Bike'),
            ('B', 'Car'),
            ('K', 'Scooter')
        ]
    )
    enrollment_date = models.DateField()
    total_fee = models.IntegerField()
    notes = models.TextField(null=True, blank=True)
    fees_paid = models.IntegerField(default=0)
    slug = models.SlugField(unique=True, blank=True)

    @property
    def balance(self):
        return self.total_fee - self.fees_paid

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        if not self.slug:  # only create slug if it's empty
            self.slug = slugify(self.name) + "-" + str(uuid.uuid4())[:4]
        super().save(*args, **kwargs)

class Payment(models.Model):
    student = models.ForeignKey(Student, on_delete = models.CASCADE)
    amountPaid = models.IntegerField()
    paymentDate = models.DateField()
    paymentMethod = models.CharField(max_length=15, 
    choices=
    [
        ('Cash', 'Cash'),
        ('Online', 'Online Payment'),
    ], default='Cash'
        )
    
    def __str__(self):
        return self.student.name
    
class Staff(models.Model) : 
    name = models.CharField(max_length=15)
    phone = models.CharField(max_length=10)
    email = models.EmailField()
    date = models.DateField(auto_now_add=True)
    slug = models.SlugField(unique=True, blank=True)

    def __str__(self):
        return self.name
    
    def save(self, *args , **kwargs):
        if not self.slug :
            self.slug = slugify(self.name) + "-" + str(uuid.uuid4())[:4]
        super().save(*args,**kwargs)

driving_mis/userAdmin/forms.py
from  django import forms
from .models import Student, Payment, Staff

class StudentRegisterForm(forms.ModelForm) :
    class Meta :
        model = Student
        exclude = ["slug"]
        fields = '__all__'

class PaymentRegistrationForm(forms.ModelForm) :
    class Meta :
        model = Payment
        fields = '__all__'

class StaffRegistrationForm(forms.ModelForm) :
    class Meta :
        model = Staff
        exclude = ["slug"]
        fields = '__all__'

driving_mis/userAdmin/views.py
from django.shortcuts import render, redirect
from .models import Student,Payment,Staff
from django.db.models import Sum  
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils.timezone import now 

@login_required
def dashboard_page(request):
    if not request.user.is_superuser:
        return redirect('userStaff:staffDashboard')
    total_students = Student.objects.count()
    total_payments = Payment.objects.count()
    total_staffs= Staff.objects.count()
    total_amount = Payment.objects.aggregate(
        total = Sum('amountPaid')
    )['total'] or 0

    recent_students = Student.objects.order_by('-enrollment_date')[:5]

    context = {
        'total_students': total_students,
        'total_staffs': total_staffs,
        'total_payments': total_payments,
        'total_amount': total_amount,
        'recent_students' : recent_students, 
    }

    return render(request, "userAdmin/dashboard_page.html", context)

# STUDENTS
@login_required
def students_page(request):
    students = Student.objects.all()
    return render(request, "userAdmin/students/student_page.html", { 'students' : students})

@login_required
def student_add(request):
    if request.method == 'POST' :
        name = request.POST['name']
        phone  = request.POST['phone']
        address  = request.POST['address']
        course  = request.POST['course']
        enrollment_date  = request.POST['enrollment_date']
        total_fee  = request.POST['total_fee']
        fees_paid  = request.POST['fees_paid']
        notes = request.POST['notes']
        Student.objects.create(
            name = name,
            phone = phone,
            address = address,
            course = course,
            enrollment_date = enrollment_date,
            total_fee = total_fee,
            fees_paid = fees_paid,
            notes = notes,
        )
        messages.success(request,'Student Added!')
        return redirect('userAdmin:students')
    return render(request, "userAdmin/students/student_add_page.html")

@login_required
def student_update(request, slug):
    student = Student.objects.get(slug=slug)
    if request.method == 'POST' :
        student.name = request.POST['name']
        student.phone  = request.POST['phone']
        student.address  = request.POST['address']
        student.course  = request.POST['course']
        student.enrollment_date  = request.POST['enrollment_date']
        student.total_fee  = request.POST['total_fee']
        student.fees_paid  = request.POST['fees_paid']
        student.notes = request.POST['notes']
        student.save()
        messages.info(request, "Student Record Updated!")
        return redirect('userAdmin:students')
    else :
        return render(request, "userAdmin/students/student_update_page.html", {"student" : student})

@login_required
def student_delete(request, slug):
    if request.method == 'POST' :
        student = Student.objects.get(slug=slug)
        student.delete()
        messages.error(request,"Student Deleted")
        return redirect('userAdmin:students')
    return redirect('userAdmin:students')

# PAYMENTS
@login_required
def payments_page(request):
    payments = Payment.objects.all()
    return render(request, "userAdmin/payments/payment_page.html", {'payments' : payments})

@login_required
def payment_add(request):
    students = Student.objects.all()
    if request.method == 'POST':
        student_slug = request.POST['student']
        amount = request.POST['amountPaid']
        date = request.POST['paymentDate']
        method = request.POST['paymentMethod']
        student_obj = Student.objects.get(slug=student_slug)
        Payment.objects.create(
            student = student_obj,
            amountPaid = amount,
            paymentDate = date,
            paymentMethod = method,
        )
        messages.success(request,"Payment Recorded!")
        return redirect ('userAdmin:payments')
    return render(request, "userAdmin/payments/payment_add_page.html", {'students' : students })

@login_required
def payment_update(request, id):
    students = Student.objects.all()
    payment = Payment.objects.get(id=id)
    if request.method == 'POST' :
        payment.amountPaid = request.POST['amountPaid']
        payment.paymentDate = request.POST['paymentDate']
        payment.paymentMethod = request.POST['paymentMethod']
        payment.save()
        messages.info(request,'Payment Record Updated!')
        return redirect('userAdmin:payments')
    return render(request, "userAdmin/payments/payment_update_page.html", {"paymentData" : payment, 'students': students})

@login_required
def payment_delete(request, id):
    if request.method == 'POST' :
        payment = Payment.objects.get(id = id)
        payment.delete()
        messages.error(request, 'Payment Record Deleted!')
        return redirect('userAdmin:payments')


# STAFFS
@login_required
def staffs_page(request):
    staffs = Staff.objects.all()
    return render(request, "userAdmin/staffs/staff_page.html", {'staffs': staffs})

@login_required
def staff_add(request):
    if request.method == 'POST':
        name = request.POST['name']
        phone = request.POST['phone']
        email = request.POST['email']
        Staff.objects.create(
            name = name,
            phone = phone,
            email = email,
        )
        messages.success(request,'Staff Added!')
        return redirect ('userAdmin:staffs')
    return render(request, "userAdmin/staffs/staff_add_page.html")

@login_required
def staff_update(request, staff_id):
    staff = Staff.objects.get(id = staff_id)
    if request.method == 'POST': 
        staff.name = request.POST['name']
        staff.phone = request.POST['phone']
        staff.email = request.POST['email']
        staff.save()
        messages.info(request, 'Staff Updated!')
        return redirect('userAdmin:staffs')
    return render(request, "userAdmin/staffs/staff_update_page.html", {"staff" : staff})

@login_required
def staff_delete(request, staff_id):
    if request.method == 'POST' :
        staff = Staff.objects.get(id=staff_id)
        staff.delete()
        messages.error(request,'Staff Deleted!')
        return redirect('userAdmin:staffs')
    return redirect('userAdmin:staffs')

driving_mis/userAdmin/templates/userAdmin/dashboard_page.html
{% extends "layout.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static "css/dashboard.css" %}">
{% endblock extra_css %}

{% block title %}
    <title>Dasboard</title>
{% endblock title %}

{% block content %}

    {% if messages %}
            <div id="messages-container">
                {% for message in messages %}
            <div class="message {{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
            </div>
    {% endif %}

    <div class="dashboard-container">

    <!-- ROW 1 : STATS -->
    <div class="dashboard-grid">
        <div class="dashboard-card">
            Students: {{total_students}}
            <small>Total Registered</small>
        </div>

        <div class="dashboard-card">
            Staff: {{total_staffs}}
            <small>Active Employees</small>
        </div>

        <div class="dashboard-card">
            Payments: {{total_payments}}
            <small>Total Transactions</small>
        </div>

        <div class="dashboard-card">
            Amount: {{total_amount}}
            <small>Total Fees Collected</small>
        </div>
    </div>

    <br>

    <!-- ROW 2 : ACTION BUTTONS -->
    <div class="dashboard-grid">
        <a href= "{% url "userAdmin:addStudent" %}" class="dashboard-action">Add Student</a>
        <a href="{% url "userAdmin:addPayment" %}" class="dashboard-action">Add Payment</a>
        <a href="{% url "userAdmin:addStaff" %}" class="dashboard-action">Add Staff</a>
    </div>

    <br>

    <!-- FULL WIDTH : RECENT REGISTRATIONS -->
    <div class="dashboard-grid">
        <div class="dashboard-full">
            <h3>Recent Registrations</h3>
            <br>
            <table class="table">
                <tr>
                        <th>Name</th>
                        <th>Date</th>
                    </tr>
                {% for student in recent_students %}
                    <tr>
                        <td>{{student.name}}</td>
                        <td>{{student.enrollment_date|date:"M d, Y"}}</td>
                    </tr>
                    {% empty %}
                        <tr>
                            <td colspan="2">No recent registrations</td>
                        </tr>
                {% endfor %}
                
            </table>
        </div>
    </div>

</div>
{% endblock content %}

{% block extra_js %}
<script src="{% static 'js/base.js' %}" defer></script>
{% endblock %}

driving_mis/userAdmin/templates/userAdmin/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Driving Institute MIS{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
    {% block extra_css %}{% endblock extra_css %}
</head>

</head>
<body>

    <!-- Top bar -->
    <div class="topbar">
        <div class="title">Driving Institute Management System</div>
        <form action="{% url 'userAdmin:logout' %}" method='POST'>
            {% csrf_token %}
            <button>Logout</button>
        </form>
    </div>

    <!-- Navigation bar -->
    <div class="nav">
        <a href="{% url 'userAdmin:dashboard' %}">Dashboard</a>
        <a href="{% url 'userAdmin:students' %}">Students</a>
        <a href="{% url 'userAdmin:payments' %}">Payments</a>
        <a href="{% url 'userAdmin:staffs' %}">Staff Management</a>
    </div>

    <!-- Main content -->
    <div class="main-content">
        {% block content %}
        {% endblock %}
    </div>

    {% block extra_js %}{% endblock %}
    
</body>
</html>