driving_mis/driving_mis/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', views.home_redirect, name='home'),
    path('login/', views.login_page, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('admin/', include("userAdmin.urls")),
    path('staffs/', include('userStaff.urls')),
]

driving_mis/userAdmin/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'userAdmin'

urlpatterns = [
    
    path('dashboard/', views.dashboard_page, name='dashboard'),
    path('students/', views.students_page, name='students'),
    path('payments/', views.payments_page, name='payments'),
    path('staffs/', views.staffs_page, name='staffs'),

    path('students/add/', views.student_add, name='addStudent'),
    path('students/update/<slug:slug>/', views.student_update, name='updateStudent'),
    path('students/delete/<slug:slug>/', views.student_delete, name='deleteStudent'),

    path('payments/add/', views.payment_add, name='addPayment'),
    path('payments/update/<int:id>/', views.payment_update, name='updatePayment'),
    path('payments/delete/<int:id>/', views.payment_delete, name='deletePayment'),

    path('staffs/add/', views.staff_add, name='addStaff'),
    path('staffs/update/<int:staff_id>/', views.staff_update, name='updateStaff'),
    path('staffs/delete/<int:staff_id>/', views.staff_delete, name='deleteStaff'),
]

driving_mis/userStaff/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'userStaff'

urlpatterns = [
    # path('', views.login_page, name='login'),
    path('/logout', auth_views.LogoutView.as_view(), name='logout'),

    path('dashboard/', views.dashboard_page, name='staffDashboard'),
    path('students/', views.students_page, name='staffStudents'),
    path('payments/', views.payments_page, name='staffPayments'),

    path('students/add/', views.student_add, name='StaffAddStudent'),
    path('students/update/<slug:slug>/', views.student_update, name='StaffUpdateStudent'),
    path('students/delete/<slug:slug>/', views.student_delete, name='StaffDeleteStudent'),

    path('payments/add/', views.payment_add, name='StaffAddPayment'),
    path('payments/update/<int:id>/', views.payment_update, name='StaffUpdatePayment'),
    path('payments/delete/<int:id>/', views.payment_delete, name='StaffDeletePayment'),

]

driving_mis/userAdmin/models.py
from django.db import models
from django.utils.text import slugify
import uuid

class Student(models.Model):
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=15)
    address = models.TextField()
    course = models.CharField(
        max_length=1,
        choices=[
            ('A', 'Bike'),
            ('B', 'Car'),
            ('K', 'Scooter')
        ]
    )
    enrollment_date = models.DateField()
    total_fee = models.IntegerField()
    notes = models.TextField(null=True, blank=True)
    fees_paid = models.IntegerField(default=0)
    slug = models.SlugField(unique=True, blank=True)

    @property
    def balance(self):
        return self.total_fee - self.fees_paid

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        if not self.slug:  # only create slug if it's empty
            self.slug = slugify(self.name) + "-" + str(uuid.uuid4())[:4]
        super().save(*args, **kwargs)

class Payment(models.Model):
    student = models.ForeignKey(Student, on_delete = models.CASCADE)
    amountPaid = models.IntegerField()
    paymentDate = models.DateField()
    paymentMethod = models.CharField(max_length=15, 
    choices=
    [
        ('Cash', 'Cash'),
        ('Online', 'Online Payment'),
    ], default='Cash'
        )
    
    def __str__(self):
        return self.student.name
    
class Staff(models.Model) : 
    name = models.CharField(max_length=15)
    phone = models.CharField(max_length=10)
    email = models.EmailField()
    date = models.DateField(auto_now_add=True)
    slug = models.SlugField(unique=True, blank=True)

    def __str__(self):
        return self.name
    
    def save(self, *args , **kwargs):
        if not self.slug :
            self.slug = slugify(self.name) + "-" + str(uuid.uuid4())[:4]
        super().save(*args,**kwargs)

driving_mis/userStaff/models.py
from django.db import models
from userAdmin.models import Student, Payment 
# Create your models here.

driving_mis/userStaff/views.py
# Create your views here.
from django.shortcuts import render, redirect
from .models import Student,Payment
from django.db.models import Sum
from django.contrib.auth import login
from django.contrib.auth.forms import AuthenticationForm   
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils.timezone import now 

@login_required
def dashboard_page(request):
    if request.user.is_superuser:
        return redirect('userStaff:dashboard')
    total_students = Student.objects.count()
    total_payments = Payment.objects.count()
    total_amount_today = Payment.objects.aggregate(
        total = Sum('amountPaid')
    )['total'] or 0

    recent_students = Student.objects.order_by('-enrollment_date')[:5]

    context = {
        'total_students': total_students,
        'total_payments': total_payments,
        'total_amount_today': total_amount_today,
        'recent_students' : recent_students, 
    }

    return render(request, "userStaff/staff_dashboard.html", context)

# STUDENTS
@login_required
def students_page(request):
    students = Student.objects.all()
    return render(request, "userStaff/students/staff_student_page.html", { 'students' : students})

@login_required
def student_add(request):
    if request.method == 'POST' :
        name = request.POST['name']
        phone  = request.POST['phone']
        address  = request.POST['address']
        course  = request.POST['course']
        enrollment_date  = request.POST['enrollment_date']
        total_fee  = request.POST['total_fee']
        fees_paid  = request.POST['fees_paid']
        notes = request.POST['notes']
        Student.objects.create(
            name = name,
            phone = phone,
            address = address,
            course = course,
            enrollment_date = enrollment_date,
            total_fee = total_fee,
            fees_paid = fees_paid,
            notes = notes,
        )
        messages.success(request,'Student Added!')
        return redirect('userStaff:staffStudents')
    return render(request, "userStaff/students/staff_student_add_page.html")

@login_required
def student_update(request, slug):
    student = Student.objects.get(slug=slug)
    if request.method == 'POST' :
        student.name = request.POST['name']
        student.phone  = request.POST['phone']
        student.address  = request.POST['address']
        student.course  = request.POST['course']
        student.enrollment_date  = request.POST['enrollment_date']
        student.total_fee  = request.POST['total_fee']
        student.fees_paid  = request.POST['fees_paid']
        student.notes = request.POST['notes']
        student.save()
        messages.info(request, "Student Record Updated!")
        return redirect('userStaff:staffStudents')
    else :
        return render(request, "userStaff/students/student_update_page.html", {"student" : student})

@login_required
def student_delete(request, slug):
    if request.method == 'POST' :
        student = Student.objects.get(slug=slug)
        student.delete()
        messages.error(request,"Student Deleted")
        return redirect('userStaff:staffStudents')
    return redirect('userAdmin:staffStudents')

# PAYMENTS
@login_required
def payments_page(request):
    payments = Payment.objects.all()
    return render(request, "userStaff/payments/staff_payment_page.html", {'payments' : payments})

@login_required
def payment_add(request):
    students = Student.objects.all()
    if request.method == 'POST':
        student_slug = request.POST['student']
        amount = request.POST['amountPaid']
        date = request.POST['paymentDate']
        method = request.POST['paymentMethod']
        student_obj = Student.objects.get(slug=student_slug)
        Payment.objects.create(
            student = student_obj,
            amountPaid = amount,
            paymentDate = date,
            paymentMethod = method,
        )
        messages.success(request,"Payment Recorded!")
        return redirect ('userStaff:staffPayments')
    return render(request, "userStaff/payments/staff_payment_add_page.html", {'students' : students })

@login_required
def payment_update(request, id):
    students = Student.objects.all()
    payment = Payment.objects.get(id=id)
    if request.method == 'POST' :
        payment.amountPaid = request.POST['amountPaid']
        payment.paymentDate = request.POST['paymentDate']
        payment.paymentMethod = request.POST['paymentMethod']
        payment.save()
        messages.info(request,'Payment Record Updated!')
        return redirect('userStaff:staffPayments')
    return render(request, "userStaff/payments/staff_payment_update_page.html", {"paymentData" : payment, 'students': students})

@login_required
def payment_delete(request, id):
    if request.method == 'POST' :
        payment = Payment.objects.get(id = id)
        payment.delete()
        messages.error(request, 'Payment Record Deleted!')
        return redirect('userStaff:staffPayments')

driving_mis/userStaff/templates/userStaff/payments/staff_payment_add_page.html
{% extends "layout.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/baseForm.css' %}">
{% endblock extra_css %}

{% block title %}
<title>Add Payment</title>
{% endblock title %}

{% block content %}

<div class="form-container">

    <form method="POST" action="{% url 'userStaff:StaffAddPayment' %}">
        {% csrf_token %}

        <label for="name">Student: </label>
        <select id="student" name="student">
            {% for student in students %}
                <option value="{{ student.slug }}">{{ student.name }}</option>
            {% endfor %}
        </select>

        <label for="amount">Amount Paid: </label>
        <input type="number" id="amount" name="amountPaid" required>

        <label for="paymentDate">Payment Date:</label>
        <input type='date' id="paymentDate" name="paymentDate"></input>

        <label for="paymentMethod">Payment Method: </label>
        <select id="paymentMethod" name="paymentMethod">
            <option value="Cash">Cash</option>
            <option value="Online">Online Payment</option>
        </select>

        <button type="submit">Add Payment</button>

    </form>

</div>

{% endblock content %}

driving_mis/userStaff/templates/userStaff/payments/staff_payment_page.html
{% extends "layout.html" %}
{% load static %}

{% block title %}
<title>Payment</title>
{% endblock title %}

{% block content %}
    {% if messages %}
        <div id='messages-container'>
            {% for message in messages  %}
                <div class="message {{message.tags}}">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}

<!-- Add Payment Button -->
<br>
<div class="header">
    <h2>Payments</h2>
    <a href="{% url 'userStaff:StaffAddPayment' %}" class="btn-add">Add Payment</a>
</div>

<div class='table-container'>
<!-- Students Table -->
    <table class="table">
        <thead>
            <tr>
                <th>Student Name</th>
                <th>Phone Number</th>
                <th>Amount Paid</th>
                <th>Payment Date</th>
                <th>Payment Method</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <!-- Example row -->
            {% for paymentData in payments %}
            <tr>
                <td>{{paymentData.student.name}}</td>
                <td>{{paymentData.student.phone}}</td>
                <td>{{paymentData.amountPaid}}</td>
                <td>{{paymentData.paymentDate}}</td>
                <td>{{paymentData.get_paymentMethod_display}}</td>
                <td class="actions-col">
                <div class="actions-wrapper">
                    <form method='GET' action='{% url 'userStaff:StaffUpdatePayment' paymentData.id %}'>
                        <button type="submit" class="action-btn edit">Edit</button>
                    </form>

                    <form action='{% url 'userStaff:StaffDeletePayment' paymentData.id %}' method='POST'> 
                        {% csrf_token %}
                        <button type="submit" class="action-btn delete" onclick= "
                        return confirm('Are you sure you want to delete payment for {{ paymentData.student.name }}?');
                        ">Delete</a>
                    </form>
                </div>
                </td>
            </tr>
            {% endfor %}
            <!-- More rows will be rendered dynamically from DB later -->
        </tbody>
    </table>
</div>
{% endblock content %}

{% block extra_js %}
<script src="{% static 'js/base.js' %}" defer></script>
{% endblock %}

driving_mis/userStaff/templates/userStaff/payments/staff_payment_update_page.html
{% extends "layout.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/baseForm.css' %}">
{% endblock extra_css %}

{% block title %}
<title>Add Student</title>
{% endblock title %}

{% block content %}

<div class="form-container">

    <form method="POST" action="{% url 'userStaff:StaffUpdateStudent' student.slug %}">
        {% csrf_token %}

        <label for="name">Name:</label>
        <input type="text" id="name" name="name" value="{{student.name|escape}}" required>

        <label for="phone">Phone Number:</label>
        <input type="text" id="phone" name="phone" value="{{student.phone}}" required>

        <label for="address">Address:</label>
        <textarea id="address" name="address">{{student.address}}</textarea>

        <label for="course">Course / Package:</label>
        <select id="course" name="course" value="{{student.course}}">
            <option value="A">Bike (A)</option>
            <option value="B">Car (B)</option>
            <option value="K">Scooter (K)</option>
        </select>

        <label for="total_fee">Total Fee:</label>
        <input type="text" id="total_fee" name="total_fee" value="{{student.total_fee}}">

        <label for="fees_paid">Fees Paid:</label>
        <input type="text" id="fees_paid" name="fees_paid" value="{{student.fees_paid}}">

        <label for="enrollment_date">Enrollment Date:</label>
        <input type="date" id="enrollment_date" name="enrollment_date" value="{{ student.enrollment_date|date:'Y-m-d' }}" required>

        <label for="notes">Notes:</label>
        <textarea id="notes" name="notes"> {{student.notes}} </textarea>

        <button type="submit">Update Student</button>

    </form>

</div>

{% endblock content %}