driving_mis/driving_mis/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', views.home_redirect, name='home'),
    path('login/', views.login_page, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('admin/', include("userAdmin.urls")),
    path('staffs/', include('userStaff.urls')),
]

driving_mis/userAdmin/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'userAdmin'

urlpatterns = [
    
    path('dashboard/', views.dashboard_page, name='dashboard'),
    path('students/', views.students_page, name='students'),
    path('payments/', views.payments_page, name='payments'),
    path('staffs/', views.staffs_page, name='staffs'),

    path('students/add/', views.student_add, name='addStudent'),
    path('students/update/<slug:slug>/', views.student_update, name='updateStudent'),
    path('students/delete/<slug:slug>/', views.student_delete, name='deleteStudent'),

    path('payments/add/', views.payment_add, name='addPayment'),
    path('payments/update/<int:id>/', views.payment_update, name='updatePayment'),
    path('payments/delete/<int:id>/', views.payment_delete, name='deletePayment'),

    path('staffs/add/', views.staff_add, name='addStaff'),
    path('staffs/update/<int:staff_id>/', views.staff_update, name='updateStaff'),
    path('staffs/delete/<int:staff_id>/', views.staff_delete, name='deleteStaff'),
]

driving_mis/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Driving Institute MIS{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
    {% block extra_css %}{% endblock extra_css %}
</head>

</head>
<body>

    <!-- Top bar -->
    <div class="topbar">
        <div class="title">Driving Institute Management System</div>
        <form action="{% url 'logout' %}" method='POST'>
            {% csrf_token %}
            <button>Logout</button>
        </form>
    </div>

    <!-- Navigation bar -->
    <div class="nav">
        <a href="{% url 'userAdmin:dashboard' %}">Dashboard</a>
        <a href="{% url 'userAdmin:students' %}">Students</a>
        <a href="{% url 'userAdmin:payments' %}">Payments</a>
        <a href="{% url 'userAdmin:staffs' %}">Staff Management</a>
    </div>

    <!-- Main content -->
    <div class="main-content">
        {% block content %}
        {% endblock %}
    </div>

    {% block extra_js %}{% endblock %}
    
</body>
</html>

driving_mis/templates/login_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
    <link rel="stylesheet" href=" {% static "css/baseForm.css" %} ">
    <style>
        body 
        { 
            font-family: Arial, sans-serif; 
            text-align: center; 
            margin-top: 100px; 
        }

        .btn 
        {   
            padding: 15px 30px; 
            background-color: #333; 
            color: #fff; 
            border: none; 
            border-radius: 5px; 
            font-size: 18px; 
            cursor: pointer; 
            text-decoration: none; 
        }

        .btn:hover 
        { 
        background-color: #555; 
        }

        .message.success {
            background-color: #28a745;   /* green */
        }

        .message.error {
            background-color: #dc3545;   /* red */
        }

        .message.info {
            background-color: #ffc107; /* yellow */
            color:#171717;
        }

                /* Messages container fixed in bottom-right */
        #messages-container {
            position: fixed;
            bottom: 20px;
            right: 20px;
            width: 300px;       /* Adjust width as needed */
            z-index: 9999;
        }

        /* Each message box */
        .message {
            padding: 15px 20px;
            margin-top: 10px;
            border-radius: 8px;
            color: #fff;
            font-weight: 500;
            box-shadow: 0 4px 8px rgba(0,0,0,0.1);
            opacity: 0.95;
            transition: transform 0.3s ease, opacity 0.3s ease;
        }
    </style>
</head>
<body>
    
    {% if messages %}
            <div id="messages-container">
                {% for message in messages %}
            <div class="message {{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
            </div>
    {% endif %}

    <h1>Welcome to Driving Institute MIS</h1>
<div class='form-container'>
    <form action=" {% url "login" %} " method='POST'>
        {% csrf_token %}
        {{form}}
        <button>Login</button>
    </form>
</div>
    <script src="{% static 'js/base.js' %}"></script>
</body>
</html>